# Change these first
owner: tensegrity-labs-admin
repo: uptime

sites:
  - name: Website (www.tensegrity-labs.com)
    url: https://www.tensegrity-labs.com
  - name: URL Shortner (tlabs.link)
    url: https://tlabs.link/test
  - name: In-house Server
    check: "tcp-ping"
    url: xen-srv.tensegrity-labs.com
  - name: Cloud Services (tcloud.dev)
    url: $TCLOUD_STATUS_URL
    headers:
      - "NC-Token: $TCLOUD_TOKEN"
  - name: Cloud Services (Onlyoffice)
    url: https://onlyoffice.tcloud.dev
  - name: GitLab (gitlab.tcloud.dev)
    url: https://gitlab.tcloud.dev
  - name: Cloud Storage (minio.tcloud.dev)
    url: https://minio.tcloud.dev
  - name: Cloud Storage API (minio-api.tcloud.dev)
    check: "tcp-ping"
    url: https://minio-api.tcloud.dev
    port: 443

status-website:
  cname: status.tensegrity-labs.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Tensegrity Labs Status
  introTitle: Tensegrity Labs Status
  introMessage: The status of Tensegrity Labs web services

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
