# Change these first
owner: tensegrity-labs-admin
repo: uptime

sites:
  - name: Website (www.tensegrity-labs.com)
    url: https://www.tensegrity-labs.com
  - name: URL Shortner (tlabs.link)
    url: https://tlabs.link/test
  - name: In-house Server
    check: "tcp-ping"
    url: xen-srv.tensegrity-labs.com
  - name: Cloud Services (tcloud.dev)
    url: https://tcloud.dev
  - name: Cloud Services (Onlyoffice)
    url: https://onlyoffice.tcloud.dev
  - name: GitLab (gitlab.tcloud.dev)
    url: https://gitlab.tcloud.dev
  - name: Cloud Storage (minio.tcloud.dev)
    url: https://minio.tcloud.dev
  - name: Cloud Storage API (minio-api.tcloud.dev)
    method: GET
    url: https://minio-api.tcloud.dev/minio/health/live

status-website:
  cname: status.tensegrity-labs.com
  logoUrl: https://www.tensegrity-labs.com/wp-content/uploads/2021/03/logo_box-e1641502133503.png
  name: Tensegrity Labs Status
  introTitle: Tensegrity Labs Status
  introMessage: The status of Tensegrity Labs web services

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
